script: bundle exec rspec spec
script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - bundle exec rspec spec
language: node_js
node_js:
  - "0.12"
before_script:
  - "gem install mime-types-data -v '3.2016.0521'"
  - 'bundle install'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'node_modules/protractor/bin/webdriver-manager update --standalone --firefox'
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - sleep 3
  - 'npm install bower'
  - 'npm install grunt'
  - 'npm install grunt-cli'
  - 'npm install grunt-protractor-webdriver'
  - 'npm install grunt-protractor-runner'
  - 'npm install grunt-express-server'
